import { Router } from 'express';
import { prisma } from '../db';
import { applyLeaveSchema } from '../validation';
import { processLeaveApplication } from '../utils/leave';
import { requireAuth, requireRole } from '../middleware/auth';

export const leavesRouter = Router();

// GET /api/leaves
leavesRouter.get('/', async (req, res, next) => {
  try {
    const { workerId } = req.query;

    const where: any = {};
    if (workerId && typeof workerId === 'string') {
      where.workerId = workerId;
    }

    const leaves = await prisma.leaveRecord.findMany({
      where,
      orderBy: { startDate: 'desc' }
    });

    return res.json(leaves);
  } catch (err) {
    next(err);
  }
});

// GET /api/leaves/:id
leavesRouter.get('/:id', async (req, res, next) => {
  try {
    const { id } = req.params;
    const leave = await prisma.leaveRecord.findUnique({
      where: { id }
    });

    if (!leave) {
      return res.status(404).json({ error: 'Leave record not found' });
    }

    return res.json(leave);
  } catch (err) {
    next(err);
  }
});

// POST /api/leaves/apply
leavesRouter.post('/apply', requireAuth, requireRole('Admin', 'Plant Manager'), async (req, res, next) => {
  try {
    const parsed = applyLeaveSchema.parse(req.body);

    const result = await processLeaveApplication(prisma, {
      workerId: parsed.workerId,
      startDate: parsed.startDate,
      endDate: parsed.endDate,
      leaveType: parsed.leaveType,
      reason: parsed.reason,
      includeWeekends: parsed.includeWeekends,
      force: parsed.force
    });

    if (!result.success) {
      return res.status(409).json(result);
    }

    return res.status(201).json(result);
  } catch (err) {
    next(err);
  }
});

// DELETE /api/leaves/:id (Cancels leave and cleans up generated attendance records)
leavesRouter.delete('/:id', requireAuth, requireRole('Admin', 'Plant Manager'), async (req, res, next) => {
  try {
    const { id } = req.params;

    const leave = await prisma.leaveRecord.findUnique({
      where: { id }
    });

    if (!leave) {
      return res.status(404).json({ error: 'Leave record not found' });
    }

    await prisma.$transaction(async (tx) => {
      // Clean up attendance records generated by this leave
      await tx.attendanceRecord.deleteMany({
        where: { leaveRecordId: id }
      });

      // Delete leave record
      await tx.leaveRecord.delete({
        where: { id }
      });
    });

    return res.json({ success: true, message: 'Leave cancelled and records updated' });
  } catch (err) {
    next(err);
  }
});
